apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activemq
  namespace:  argocd999
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: chime999
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    chart: activemq
    repoURL: https://cwops.jfrog.io/artifactory/api/helm/qcomm-helm
    targetRevision: 0.1.7
    helm:
      values: |
        localNodeTimezone: false
        timezone: "Europe/Paris"
        global:
          imagePullSecrets:
            - regcred
        fullnameOverride: "activemq"
        ingress:
          hosts:
            - amq.apps.rana.l9ri.p1.openshiftapps.com
          tls: [] # for openshift
          annotations: 
            route.openshift.io/termination: edge
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi

