apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chime999
  namespace: argocd999
spec:
  destination:
    namespace: argocd999
    server: https://kubernetes.default.svc
  project: default
  source:
    path: OCP/support
    repoURL: https://github.com/mishrasanjib/rana-chime-aws
    targetRevision: HEAD
    helm:
      values: |
        ingressSuffix: "apps.rana.l9ri.p1.openshiftapps.com"
        imagePullSecrets: "regcred"
        timezone: "Europe/Paris"
